const ADMIN = "ADMIN";
const STUDENT = "STUDENT";
const MATERIAL_DESIGNER = "MATERIAL_DESIGNER";
const MATERIAL_REVIEWER = "MATERIAL_REVIEWER";

export default {
  ADMIN,
  STUDENT,
  MATERIAL_DESIGNER,
  MATERIAL_REVIEWER
};